apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clickhouse-pvc
  namespace: data-platform
spec:
  storageClassName: my-storage-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse-internal
  namespace: data-platform
spec:
  selector:
    app: clickhouse
  ports:
    - name: http
      port: 8123
      targetPort: 8123
    - name: native
      port: 9000
      targetPort: 9000
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: tabix-external
  namespace: data-platform
spec:
  selector:
    app: tabix
  ports:
    - name: tabix
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse-deployment
  namespace: data-platform
  labels:
    app: clickhouse
spec:
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      containers:
        - name: clickhouse
          image: clickhouse/clickhouse-server
          ports:
            - containerPort: 8123
            - containerPort: 9000
          volumeMounts:
            - mountPath: /var/lib/clickhouse
              name: clickhouse-storage
      volumes:
        - name: clickhouse-storage
          persistentVolumeClaim:
            claimName: clickhouse-pvc

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tabix-deployment
  namespace: data-platform
  labels:
    app: tabix
spec:
  selector:
    matchLabels:
      app: tabix
  template:
    metadata:
      labels:
        app: tabix
    spec:
      containers:
        - name: tabix
          image: spoonest/clickhouse-tabix-web-client
          ports:
            - containerPort: 80



