kafka:
  topics:
    movie: tmdb.movies.raw
    tv_series: tmdb.tv_series.raw
    person: tmdb.people.raw
  server:
    bootstrap_servers: kafka-internal:9092
  producer:
    retries: 3
    max_buffer: 10