storage:
  delta_lake:
    minio_endpoint: "http://minio-internal:9000"
    minio_access_key: "minio"
    minio_secret_key: "minio123"
    target_name_folder:
      movie: "movies"
      tv_series: "tvseries"
      person: "people"
    tables:
      bronze_layer:
        valid_base_path: "s3a://deltalake/bronze/valid"
        invalid_base_path: "s3a://deltalake/bronze/invalid"
      silver_layer:
        valid_base_path: "s3a://deltalake/silver/valid"
        invalid_base_path: "s3a://deltalake/silver/invalid" # Not used yet
    checkpoints:
      write_to_delta:
        valid_base_path: "s3a://deltalake/silver/to_delta/_checkpoints/_valid"
        invalid_base_path: "s3a://deltalake/silver/to_delta/_checkpoints/_invalid" # Not used yet
      write_to_clickhouse:
        valid_base_path: "s3a://deltalake/silver/to_clickhouse/_checkpoints/_valid"
        invalid_base_path: "s3a://deltalake/silver/to_clickhouse/_checkpoints/_invalid" # Not used yet

  clickhouse:
    host: "clickhouse-internal"
    port: 8123
    username: "default"
    password: ""
    jdbc_driver: "com.clickhouse.jdbc.ClickHouseDriver"
    native_driver: "com.clickhouse.spark.ClickHouseCatalog"
    database: "silver_layer"
    tables:
      movie: "movies"
      person: "people"
      tv_series: "tv_series"

  redis:
    host: "redis-internal"
    port: 6379
    keys:
      dedup_batch_version: "dedup_batch_version"

  neo4j:
    url: url,
    username: username,
    password: password
    database: database
    instance_id: instance_id
    instance_name: instance_name
    batch_size: 10

  pinecone:
    api_key: api_key
    index_name: index_name,
    namespace:
      movie: movie_namespace
      tv_series: tv_series_namespace
      person: person_namespace

spark:
  app_name_1: "run_dedup_timestamp"
  app_name_2: "write_to_clickhouse"
  app_name_3: "write_to_neo4j"
  app_name_4: "write_to_pinecone"